apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        ingress: enabled
        app: {{ .Release.Name }}-pod
    spec:
      containers:
      - image: nginx:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: {{ .Chart.Name }}-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/cache/nginx/
          name: cache-volume
        - mountPath: /var/run/
          name: pid-volume
      volumes:
      - emptyDir: {}
        name: cache-volume
      - emptyDir: {}
        name: pid-volume
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret | quote }}
