apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: {{ .Values.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.url }}
